### PR TITLE
Publication list and citation templates

### PR DESCRIPTION
**Pull request by spl**
This implements publication lists in a more Hakyll-y way and fixes various things about the metadata in the publication summary `.md` files.

Instead of generating summary pages and lists directly from the `.bib`, this PR generates this from `.md` files, one for each publication and one for each year. The lists can be sorted and filtered using information from each citation.

It's not necessarily ideal to have a bunch of empty (for publications) or simple (for year groups) `.md` files, but it makes things a lot easier in Hakyll. There may be better ways that I haven't yet discovered, but this does work pretty well.

The majority of this work is towards #14. Tags and tag lists should be easy using this foundation.

### CODE REVIEW

**Comment by edwardabraham** [comment]
We won't need all the references in the bib file (only the ones that appear on the website). A reasonable workflow would be to add a reference to the bib file (if required), and then make an md file with the additional information needed by the website (if you wanted the reference to appear on the website). 

It would be unreasonable for all references in the bib file to have to have an associated md file. We use the bibtex for many projects, well beyond the website. I assume that references in the bib that don't appear on the website don't cause trouble? (I can't review the diff in github because of the number of files!).

**Comment by spl** [comment]
> We won't need all the references in the bib file (only the ones that appear on the website). A reasonable workflow would be to add a reference to the bib file (if required), and then make an md file with the additional information needed by the website (if you wanted the reference to appear on the website).

I thought as much.

> It would be unreasonable for all references in the bib file to have to have an associated md file. We use the bibtex for many projects, well beyond the website.

Okay. I just ran a quick script to create all the `.md` files. As it is now, it's been helping me do the publication list with the refs for all the publication year groups.

> I assume that references in the bib that don't appear on the website don't cause trouble?

No, they don't. My previous approach—attempting to detect if the `.md` file existed—was more complicated, and I was less confident about it working for all situations. Hakyll does not have a nice way to deal with possibly non-existent files. So, I think this approach is better.

> (I can't review the diff in github because of the number of files!).

Yes, that's unfortunate.

Do you want me to remove all `publications/*.md` files from the PR?

**Comment by edwardabraham** [comment]
Thanks @spl, that seems like it will work well. Maybe just keep abraham_*,
berkenbusch_*, neubauer_*, richard_*, thompson_* to get us started ...

**Comment by spl** [comment]
> Maybe just keep abraham_*, berkenbusch_*, neubauer_*, richard_*, thompson_* to get us started ...

Sure, thanks!

**Comment by spl** [comment]
@edwardabraham I removed the other files. The diff now shows up on (on github.com at least).

**Comment by spl** [comment]
Correction to this PR: I said this was mostly for #14, but it was also for #12, as I describe in a comment on that issue.

**Comment by edwardabraham** [comment]
Thanks

**Comment by edwardabraham** [comment]
Successfully rendering :)
screenshot from 2015-07-17 21 44 03

**Comment by spl** [comment]
Great!

**Pull request merged**
